### ISSUE TITLE
Documentation not available anymore (404)

### ISSUE THREAD

**Issue by jean553** [uuid-rs/uuid#128]
Hi,

I get a 404 when checking the doc: https://doc.rust-lang.org/uuid.

**Comment by Dylan-DPC** [comment]
Hey

Thanks for reporting this. We will fix this as soon as possible.

**Comment by kinggoesgaming** [comment]
we essentially need to remove this line https://github.com/uuid-rs/uuid/blob/master/src/lib.rs#L101-103
