### ISSUE TITLE
Implementation of Uuid version 2 missing?

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#134]
Going through lib.rs, I didnt see the implementation for it, although the `UuidVersion` does have a variant for it.

**Comment by kinggoesgaming** [comment]
After reading the Uuid RFC, I now release that v2 doesnt exist anymore...

Closing

**Comment by Dylan-DPC** [comment]
From wiki: 
>>> RFC 4122 reserves version 2 for "DCE security" UUIDs; but it does not provide any details. For this reason, many UUID implementations omit version 2. However, the specification of version 2 UUIDs is provided by the DCE 1.1 Authentication and Security Services specification.[4]

**Comment by kinggoesgaming** [comment]
I will reopen for now... we might end up implementing this

**Comment by thedrow** [comment]
I think it is safe to close and never implement this.

Nobody I know is using v2.
