### ISSUE TITLE
Add a version of `Uuid::from_fields` that can't fail

### ISSUE THREAD

**Issue by luser** [uuid-rs/uuid#150]
[`Uuid::from_fields`](https://docs.rs/uuid/0.6.0-beta/uuid/struct.Uuid.html#method.from_fields) takes an `&[u8]` for `d4`, so it will return an error if `d4` is not 8 bytes in length. Every time I've used this method I've had an 8 byte array to hand, so it seems silly to have to call `unwrap` on the result. It would be nice if there was a version of this like `fn from_fields(d1: u32, d2: u16, d3: u16, d4: &[u8; 8]) -> Uuid`.

I realize that working with arrays is sort of a pain in Rust for several reasons. Once [the const generics RFC](http://rust-lang.github.io/rfcs/2000-const-generics.html) gets implemented it should make some things simpler, like making it possible to have a method on slices that returns an array reference of a certain size.

**Comment by Dylan-DPC** [comment]
Hi Ted,

Thanks. We will look into this. Instead of having seperate functions, I would prefer if we could use generics for this, if possible. 

The earliest we can get this implemented & released is either 0.6.1 or 0.7.0. 

Also you are free to send us a PR implementing this.

**Comment by luser** [comment]
I'm not sure what precisely you'd want to do with generics here, can you clarify?

**Comment by Dylan-DPC** [comment]
I was thinking if we could have just one function that returns the UUID irrespective of data. But I think that won't be possible. Will add the function as you proposed.

**Comment by KodrAus** [comment]
It's not quite the same as the proposed `from_fields` method (since it takes the complete 16 byte array) but #145 offers an infallible way to get a `Uuid` from its raw representation.

**Comment by luser** [comment]
Oh, that is indeed very similar. In the uses I've found I can't just pass `[u8; 16]` because I'm reading the data from a file and it might need to be byte-swapped, unfortunately.

**Comment by kinggoesgaming** [comment]
> I'm reading the data from a file and it might need to be byte-swapped, unfortunately.

I think that's a niche case, that should technically be handled by the library user before passing it to the library.

**Comment by luser** [comment]
> I think that's a niche case, that should technically be handled by the library user before passing it to the library.

I am doing so, I just then don't have a method on `Uuid` I can call without needing to call `unwrap` on the result.

**Comment by kinggoesgaming** [comment]
@luser Can I see an example of how you are using this? Perhaps it might help get a better understanding on this

**Comment by luser** [comment]
Sure. This code hasn't actually landed anywhere yet, but it's a proposed patch to `goblin`:
https://github.com/luser/goblin/blob/b541e9584322c7e9c8e04b89db6d9be14d77e5c0/src/pe/debug.rs#L106

**Comment by Dylan-DPC** [comment]
Looking again at this, i feel that having a similar method with the only change being a different return type doesn't make much sense to me. It will add more cost ot the maintainence later and there isn't much gain including it. We could provide a function to unwrap but then it will be the same as calling unwrap from outside and there is no visible gain in it.

**Comment by luser** [comment]
You are probably right. I think in the future when we have const generics and it's possible to easily get a reference to an array of a specific size from a slice designing APIs that use exactly-sized array references will be more ergonomic.
