### ISSUE TITLE
Custom RNGs

### ISSUE THREAD

**Issue by dicej** [uuid-rs/uuid#153]
According to the [docs](https://docs.rs/uuid/0.6.0/uuid/struct.Uuid.html), it should be possible to use the `rand::Rand` trait's `rand()` method to generate a v4 UUID using a custom RNG:

> If you'd like to use a custom generator, don't use this method: use the rand::Rand trait's rand() method instead.

However, as of https://github.com/uuid-rs/uuid/commit/addaecd0fc9a1dbb053420ff91ed61ec1fc31395, `Uuid` no longer implements `rand::Rand` even if v4 support is enabled.  Is there some other mechanism to specify a custom RNG?

**Comment by kinggoesgaming** [comment]
I think we will need to do a little research on this. Perhaps we will provide a temporary fix until `rand` is stabilized and we can make `rand` a public dependency. 

> as of addaecd, Uuid no longer implements rand::Rand even if v4 support is enabled.
This is actually not true. The implementation still exists, however its just not exposed to the library user.

**Comment by adaszko** [comment]
I have the same problem as @dicej.  My use case is to seed the RNG with a fixed value in order to keep my tests deterministic where the tested code generates a lot of UUIDv4 (#100).

**Comment by asajeffrey** [comment]
This is impacting servo, which uses a custom RNG (https://github.com/servo/servo/blob/master/components/rand/lib.rs) which we use among other things to generate uuids. AFAICT there's now no way to do this.
