### ISSUE TITLE
Provide the prelude module

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#166]
# Description
Introduce the `prelude` module. 

# Feature Request
This should be considered a part of the refactor process. This will allow library users to have the same layout as the current root mod, but will allow us to move various pieces of code into separate modules without continuously breaking the users.

# Other
#124

**Comment by kinggoesgaming** [comment]
I have a question here: should I `cfg_if` the version Uuid constructors? or should that be part of a separate refactor PR?

**Comment by KodrAus** [comment]
Do you think we need to expose multiple modules in `uuid` at all or just use them as a way to organise the source internally?

**Comment by kinggoesgaming** [comment]
I opened this issue to gather ideas on it and get opinions from you all

**Comment by kinggoesgaming** [comment]
ok thoughts on the prelude... currently I will expose the following in the prelude:

`Uuid`, `UuidBytes`, and `UuidVariant`

I was thinking of adding `UuidVersion` but we still have #133 to resolve. As per the adapters and various version specific items are not included until I have further refactors, incase any of them have breaking changes. I specifically think that v1 **might** but its still an other topic there

**Comment by KodrAus** [comment]
Hmm, I'm not sure I get the value here. In most cases users will just `use uuid::Uuid` so what does the prelude really offer?
