### ISSUE TITLE
Require atleast two review approvals before merge

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#169]
As per discussion on [gitter](https://gitter.im/uuid-rs/Lobby/archives/2018/03/01), we would require atleast two approvals.

Github gives a greenlight on atleast one, which won't be good enough for us. Fortunately `bors` does have a configuration option that we can enable.

Related: https://bors.tech/documentation/

**Comment by KodrAus** [comment]
Thanks @kinggoesgaming! Is it also possible to by-pass the required number of reviewers if folks get busy and we can't get enough timely reviews?

**Comment by kinggoesgaming** [comment]
I will test it in a separate dummy repository and check this for you

**Comment by kinggoesgaming** [comment]
I havent checked the dummy repo thing yet, but I thought about it, I think (unless its a critical bugfix), we have a 1 day wait before merges

**Comment by kinggoesgaming** [comment]
done
