### ISSUE TITLE
Support V4 Uuids from arbitrary random bytes

### ISSUE THREAD

**Issue by KodrAus** [uuid-rs/uuid#170]
**Note: for support questions, please use [gitter] or [users forums]**. This 
repository's issues are reserved for feature requests and bug reports.

[gitter]: https://gitter.im/uuid-rs/Lobby
[users forums]: https://users.rust-lang.org

**I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note 
  at the top of this template.

# Description

I thought we could flesh out our solution to creating uuids using alternative `Rng`s without having to make `rand` a public dependency.

## `new_v4_bat_scooter_name_not_important`

https://github.com/servo/servo/issues/20306 suggested a `new_v4_from_bytes` method as a workaround to needing to make `rand` a public dependency. Following the naming convention for other constructors, it might look like:

```rust
fn new_v4_from_bytes(b: &[u8]) -> Result<Uuid, ParseError>;
```

```rust
let uuid = Uuid::new_v4_from_bytes(b).expect("invalid length");
```

It would be nice to use `[u8; 16]` as the source instead of `&[u8]` so we can make the method infallible. It would be a bit inconsistent to use `fn new_v4_from_bytes(b: [u8; 16])` since we already have `fn from_bytes(b: &[u8])`. `new_v4_from_uuid_bytes` is a bit of a nasty name. So for now it could be:

```rust
fn new_v4_bat_scooter_name_not_important(b: [u8; 16]) -> Uuid;
```

```rust
let uuid = Uuid::new_v4_bat_scooter_name_not_important(b);
```

We could even go ahead and name it something like `new_v4_from_rng_bytes([u8; 16])` and deprecate it once `rand` is stable in favour of `Rand::rand`.

## `Builder`
Edit: Moved to a seperate issue #171 

Related to: #153 

cc: @nox @kinggoesgaming @Dylan-DPC

**Comment by kinggoesgaming** [comment]
> We could even go ahead and name it something like `new_v4_from_rng_bytes([u8; 16])` and deprecate it once rand is stable in favour of `Rand::rand`.

I like this name, as it clearly gets the meaning across. One thing I think that should be added to this is that we add a `#[unstable] attribute so that users are aware why this function exists, as well as that it will be deprecated or removed when `rand` reaches `1.0`

**Comment by nox** [comment]
I would use `random` instead of `rng` in the name. What do you mean by `#[unstable]`?

**Comment by kinggoesgaming** [comment]
wait nevermind, ignore that `#[unstable]` I sometimes forget that `unstable` is `std` specific attribute

**Comment by Dylan-DPC** [comment]
Will give it a try today :)

**Comment by kinggoesgaming** [comment]
done
