### ISSUE TITLE
Use copy_from_slice instead of copy_memory

### ISSUE THREAD

**Issue by nox** [uuid-rs/uuid#173]
There is no need to write our own `copy_memory` method, we can just use [`<[_]>::copy_from_slice`](https://doc.rust-lang.org/std/primitive.slice.html#method.copy_from_slice) which can be implemented in a more optimised way by the standard library.

**Comment by kinggoesgaming** [comment]
So testing it, it seems our `copy_memory` function is faster than builtin `<[_]>::copy_from_slice`

Results from `cargo +nightly bench --all-features`:
https://gist.github.com/kinggoesgaming/25a5240ea8741524cdc8dc588ed6b046

**Comment by KodrAus** [comment]
Hmm, I think this might be a bit of test noise, it looks like both methods are emitting the same assembly.

**Comment by kinggoesgaming** [comment]
Seemingly it was test noise or just my computer being funny... it is generally faster, but anywhere it is slow, its only slowly by 1-2 nanosecs

**Comment by kinggoesgaming** [comment]
#175
