### ISSUE TITLE
Make uuid like i32,f64,u8 etc. Can create const value.

### ISSUE THREAD

**Issue by mokeyish** [uuid-rs/uuid#183]
```
const A: Uuid = Uuid{bytes:[70, 235, 208, 238, 14, 109, 67, 201, 185, 13, 204, 195, 90, 145, 63, 62]}
```

But the bytes is private  . Could you provide a better solution to create a const uuid value.

**Comment by Dylan-DPC** [comment]
Hey. 

Have you looked at  [from_random_bytes()](https://github.com/uuid-rs/uuid/pull/172)? It was added to 0.6.2 releae and might solve your problem. 

Also if you need help you can join us on [gitter](https://gitter.im/uuid-rs).

**Comment by mokeyish** [comment]
@Dylan-DPC Hey ,I have impleted the  create const uuid marcro. by#184
for exmaple
```
const SAMPLE:Uuid = uuid!("F9168C5E-CEB2-4FAA-B6BF-329BF39FA1E4");
```

**Comment by kinggoesgaming** [comment]
I think we can move this to post-`1.0.0` release, as that where I want to help support (optional nightly) features..

**Comment by kinggoesgaming** [comment]
closing this as it has moved out of `uuid` crate into [`uuid_macro`](https://github.com/uuid-rs/uuid_macro)
