### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#204]
Currently thats only point missing from the `Community profile`.

**Comment by KodrAus** [comment]
It would be great to have some details about how we maintain `uuid` with some kind of ramp for new folks that want to get involved in the project. [Rust's CONTRIBUTING.md](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) is pretty substantial but might offer a basic format we could follow.

**Comment by The-King** [comment]
testing team ping... (sorry for all the pings team) 

@uuid-rs/uuid

**Comment by kinggoesgaming** [comment]
Nope it don't work :cry:
