### ISSUE TITLE
Tracker: Rust 2018 Edition

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#229]
The is going to be the tracking issue about how we deal with the upcoming 2018 edition of Rust

**Comment by Dylan-DPC** [comment]
We have 2018 support on the [2018 edition branch](https://github.com/uuid-rs/uuid/tree/feature/2018-edition).

**Comment by kinggoesgaming** [comment]
The primary 2018 changes are now merged.. this can be closed in favor of individual issues.
