### ISSUE TITLE
uuid documentation link broken

### ISSUE THREAD

**Issue by Dushistov** [uuid-rs/uuid#251]
http://docs.rs/uuid lead to https://docs.rs/uuid/0.6.5/uuid/ (after redirection),
which gives "The requested resource does not exist".

**Comment by kinggoesgaming** [comment]
This is a docs.rs issue as they haven’t yet updated to `1.26.0` release compiler, and the `u128` implementation is breaking the docs. 

Until they fix that you can always depend on the crate and use `cargo doc` to have your local copy

**Comment by kinggoesgaming** [comment]
as of now it’s working
