### ISSUE TITLE
Make serde_test an optional dependency

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#253]
**Describe the bug**
`serde_test` and transitively `serde` is being built for testing, even when we dont have `serde` added as a feature gate for test builds.

Adding a `optional = true` and accordingly using a `cfg` attribute should help

**To Reproduce**
1. Run `cargo test`

**Expected behavior**
Expected only non feature-dependent tests to build

**Screenshots**
N/A

**Specifications (please complete the following information):**
- Target: N/A
- Version [e.g. 1.0]: `0.6.0`+
- Features Enabled: `serde` (expected)

**Additional context**
https://github.com/uuid-rs/uuid/blob/master/Cargo.toml#L59-L60

**Other**
N/A

**Comment by kinggoesgaming** [comment]
So testing around with this locally, found the following: 
- `dev-dependencies` cannot be optional.
- `[target."cfg()"]` syntax only accepts `dependencies`

I don't know how to proceed from here

**Comment by Dylan-DPC** [comment]
Closing this as we can't fix and we are fine with it as is since it is a dev dependency.
