### ISSUE TITLE
Make Uuid a newtype

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#266]
We are using `Uuid` as if its a new type. We should just make it a new type. 

This *might* add additional optimizations that revolve around new types.

**Comment by Dylan-DPC** [comment]
@nox yep which was my concern as well, but i guess he needs it for adapter stuff.

**Comment by kinggoesgaming** [comment]
I don't need it per second but just want to have a consist structure

**Comment by kinggoesgaming** [comment]
@nox 
> Note that this won't bring any additional optimisations compared to having a single field struct.

Hence the *`might`*

**Comment by kinggoesgaming** [comment]
#268
