### ISSUE TITLE
Delete gh-pages branch

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#267]
`gh-pages` is a vestigial branch from when the repository used to exist in `rust-lang-nursery`. It has not been updated since the move. The travis token was invalidated with the move and when the `.travis.yml` cleanup was done, the token was removed aswell.

**Comment by Dylan-DPC** [comment]
Deleted 
![Uploading image.png…]()
(proof :stuck_out_tongue: )
