### ISSUE TITLE
Suggestions for making it easier to contribute

### ISSUE THREAD

**Issue by Marwes** [uuid-rs/uuid#273]
**Describe the bug**
When submitting #270 I expected that it would be a quick and painless change which would either get merged quickly or not at all (either would be fine, given appropriate motivation). What I found instead is that I got bogged down in trying to match various style requirements. So what should have been a 5 minute change ended up being 15+ minutes instead.

### Issues

* The PR template suggests that an issue should always be created for all PRs. 
**Suggestion** Don't require this for small changes, anything discussed on the issue can just as well be discussed on the PR.

* GitCop is overly pedantic.
**Suggestion** Having a specific style for commit messages can be nice to generate documentation (I know, I tend to use it myself) but it also shouldn't be required since some changes may not warrant a specific mention. At least the `scope` part be optional in case there is no obvious context.

* Working on a feature branch (`breaking`)
**Suggestion** The other issues are more of nits but this is a bigger problem. It is not clear at all that a separate branch than `master` is used to develop on which forced me to throw away my changes and start over from scratch. Granted, I could copy paste them to redo everything in this case but I really shouldn't have had to do it in the first place. Keeping master up-to-date and back-porting changes as necessary is much friendlier to outside contributors.

Mind you, I do get why one would want to enforce things like this, but given the small scope of this crate I personally don't believe this overhead to be worth it and now that I know about these extra hurdles it does make me pause when I think about making contributions in the future.

**To Reproduce**
Attempt to submit a PR to the repository.

**Expected behavior**
I can submit a PR without (at least for small changes) quickly and without overhead.

**Comment by Dylan-DPC** [comment]
> Suggestion Don't require this for small changes, anything discussed on the issue can just as well be discussed on the PR.

I agree with this, especially changes which are not introducing a new "concept/feature". 

> Suggestion Having a specific style for commit messages can be nice to generate documentation (I know, I tend to use it myself) but it also shouldn't be required since some changes may not warrant a specific mention. At least the scope part be optional in case there is no obvious context.

Tbh, I don't know how GitCop ended up being integrated as we never discussed the need for it. Yeah i find it really annoying. 

> Suggestion The other issues are more of nits but this is a bigger problem. It is not clear at all that a separate branch than master is used to develop on which forced me to throw away my changes and start over from scratch. Granted, I could copy paste them to redo everything in this case but I really shouldn't have had to do it in the first place. Keeping master up-to-date and back-porting changes as necessary is much friendlier to outside contributors.

Maintaining the next release + breaking changes on the same branch gets messy. When we started with this approach it was fine because both branches weren't that divergent so you could change the target branch for most PRs and things were fine. But recently, we have done a lot of refactoring to the code which makes it difficult. This is just temporary till we hit 0.7 release and then we will look how to improve the "DX"

Thanks for reporting this.

**Comment by Marwes** [comment]
> About gitcop: currently it's not required. However before 1.0 I want to standardize on that for changelog purposes. Right now it only shows that message you can ignore it for now.

I often want to change what ends up in the changelog anyway so I don't enforce this as I can use the merge commit to write `feat(abc): def` (that can be easy to forget though).

I find it can be nice to not follow the style as well for intermediate commits as the message may be informative for someone looking through the history/bisecting but it wouldn't be interesting in the changelog (and refactor/chore is not applicable either).

**Comment by Dylan-DPC** [comment]
I don't see a huge gain in having "systematic stylised commit messages". I just find it overkill.

**Comment by kinggoesgaming** [comment]
Regarding issues for every PR

I think you are right. However anything that does touch the public API needs a discussion as it has stability and maintenance burden. So the PR template will definitely adjusted for it

**Comment by kinggoesgaming** [comment]
> I don't see a huge gain in having "systematic stylised commit messages". I just find it overkill.

Hmm right it's just a webhook I'll disable it

**Comment by kinggoesgaming** [comment]
GitCop is disabled

**Comment by Marwes** [comment]
Forcing everything to be rustfmt'ed is also problematic, especially if it uses the latest nightly as it is very unlikely that anyone submitting a PR has that exact version installed.

**Comment by kinggoesgaming** [comment]
We haven't had any problem with this so far. Generally, we let it as a final commit that does fix the format.

It gives the user an opportunity to update their nightly  :P

**Comment by kinggoesgaming** [comment]
All the given points have been addressed
