### ISSUE TITLE
Formatting adapter cfg(feature = "const_fn")] fns aren't const fn's

### ISSUE THREAD

**Issue by huonw** [uuid-rs/uuid#309]
**Describe the bug**

There's a variety of duplication for `#[cfg(feature = "const_fn")]` and `#[cfg(not(feature = "const_fn"))]` in https://github.com/uuid-rs/uuid/blob/master/src/adapter/mod.rs, but none of the former are actually `const fn`s, e.g. https://github.com/uuid-rs/uuid/blob/c61efa4aac132296d968fdd9225f9cba89b8e0ac/src/adapter/mod.rs#L83-L85

**To Reproduce**
1. Look at https://github.com/uuid-rs/uuid/blob/master/src/adapter/mod.rs
2. Search for `const fn` (0 matches) and `cfg(feature = "const_fn")` (12 matches)

**Expected behavior**

The `#[cfg(feature = "const_fn")]` functions to be `pub const fn`

**Specifications:**
- `master` branch (but also true on `breaking`)

**Comment by kinggoesgaming** [comment]
oh boy you caught a failed copy-pasta!! :flushed: 

 I will get this fixed today...
