### ISSUE TITLE
Version number more than 5 returned for UUID

### ISSUE THREAD

**Issue by tirkarthi** [uuid-rs/uuid#322]
**Describe the bug**

The version for UUID "481a8de5-f0d1-f211-b425-e41f134196da" seems to return 15 while 1 to 5 are the valid versions. This is reported as a bug in CPython https://bugs.python.org/issue34732 . I tried with Java 9 and this library that seem to produce same output.

**To Reproduce**

```rust

// src/main.rs

extern crate uuid;
use uuid::Uuid;

fn main() {
    let my_uuid = Uuid::parse_str("481a8de5-f0d1-f211-b425-e41f134196da").unwrap();
    println!("Parsed a version {} UUID.", my_uuid.get_version_num());
    println!("{}", my_uuid);
}
```

**output**

```
Parsed a version 15 UUID.
481a8de5-f0d1-f211-b425-e41f134196da
```

**Expected behavior**

Is there any validation done for the version number?

**Specifications:**
- RFC section : https://tools.ietf.org/html/rfc4122#section-4.1.3

**Other**

https://bugs.python.org/issue34732

Thanks

**Comment by KodrAus** [comment]
Hi @tirarthi! There is an alternative [`get_version`](https://docs.rs/uuid/0.7.1/uuid/struct.Uuid.html#method.get_version) method that will only return an RFC1422 specified version (with the addition of a `Nil` version).

**Comment by tirkarthi** [comment]
Thanks, it works as expected. Closing it.

**Comment by kinggoesgaming** [comment]
I think the documentation should be improved to make sure people dont mess this up.
