### ISSUE TITLE
Serialize impl and Display impl yields different case

### ISSUE THREAD

**Issue by Marwes** [uuid-rs/uuid#323]
**Describe the bug**

By default `Uuid`s gets serialized with lowercase but their `fmt::Display` writes the uuid in uppercase.

https://github.com/uuid-rs/uuid/blob/10e1b423aec4d118a1b162448f6289631c661bdf/src/serde_support.rs#L23

https://github.com/uuid-rs/uuid/blob/f414b351055c8cdae966e8758f6bd6a92820cda4/src/adapter/core_support/mod.rs#L105

**Expected behavior**
Making these do the same would make the behavior be less surprising.

**Specifications (please complete the following information):**
- Version 0.7

**Comment by kinggoesgaming** [comment]
Thanks @Marwes for the report. That is indeed a bug. It should be lowercase by default

**Comment by Dylan-DPC** [comment]
Hi @Marwes you are free to submit a PR that fixes it. Else will get it done myself whenever possible.

**Comment by Marwes** [comment]
Wait, no this is actually correct. Both implementations use lower case I just got things mixed up with a Uuid wrapper I have which defaults to uppercase :(
