### ISSUE TITLE
Tracker: Slog fix for 1.22 

### ISSUE THREAD

**Issue by Dylan-DPC** [uuid-rs/uuid#328]
Slog released a minor version which bumped the minimum version to 1.26.1. This tracks their next release which will fix the issue. 

This is a tracking issue for https://github.com/slog-rs/slog/issues/188

Related PRs: 
#327

**Comment by Dylan-DPC** [comment]
Thanks @ubnt-intrepid will close this issue :+1:

**Comment by kinggoesgaming** [comment]
reopening as we havent removed the duct tape from our repo tests
