### ISSUE TITLE
support the winapi-rs crate by implementing `std::convert::From<GUID>`.

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#333]
_Originally posted by @lzybkr in https://github.com/uuid-rs/uuid/issues/277#issuecomment-426824514_

**Comment by KodrAus** [comment]
Adding `from_guid` and `to_guid` methods to `Uuid` behind a feature gate (could just use `winapi`  as an optional dependency) could do this:

```toml
winapi = { version = "0.3", optional = true }
```

```rust
#[cfg(feature = "winapi")]
mod guid {
    use super::Uuid;
    use winapi::shared::guiddef::GUID;

    impl Uuid {
        pub fn from_guid(guid: GUID) -> Self;
        pub fn to_guid(&self) -> GUID;
    }
}
```

**Comment by KodrAus** [comment]
I think explicit methods on `Uuid` would be preferable to a `From` impl in this case.

**Comment by Redrield** [comment]
I could try to pick this up

**Comment by Dylan-DPC** [comment]
@Redrield yeah sure . Go ahead :+1:

**Comment by Redrield** [comment]
@Dylan-DPC  Do you want this done with a From impl or with methods on Uuid?
