### ISSUE TITLE
Add wasm support to rust stable/beta

### ISSUE THREAD

**Issue by Dylan-DPC** [uuid-rs/uuid#352]
_Originally posted by @Dylan-DPC in https://github.com/uuid-rs/uuid/pull/351#issuecomment-443429508_

Currently stdweb is broken on stable and fixed in https://github.com/koute/stdweb/commit/. This issue will be closed once a new release is cut and we depend on it.

**Comment by kinggoesgaming** [comment]
`stdweb@0.4.13` is now available

**Comment by Dylan-DPC** [comment]
we do not depend on it though, better to explicitly mention "stdweb = 0.4.13" in our Cargo.toml
