### ISSUE TITLE
version 6, v6, uuidv6 support

### ISSUE THREAD

**Issue by mitchtbaum** [uuid-rs/uuid#354]
[uuidv6](https://bradleypeabody.github.io/uuidv6/) was mentioned in a [ULID](https://github.com/ulid/spec) issue
(linked today from https://news.ycombinator.com/item?id=18768909)

**Comment by kinggoesgaming** [comment]
For now I am closing this. If ever in the future a v6 uuid is formalized, a relevant issue will be opened.

**Comment by errhammr** [comment]
Sorry for waking a sleeping dragon. I have a [function to convert any UUIDv1 into a v6 one](https://codeberg.org/errhammr/easy-uuid-v1/src/commit/740c5fa61790a86fbfeae9073252ff212dea1026/src/lib.rs#L36-L57). Maybe it'll help someone.
