### ISSUE TITLE
Custom Debug for UUID

### ISSUE THREAD

**Issue by mitsuhiko** [uuid-rs/uuid#356]
**Is your feature request related to a problem? Please describe.**
Currently when embedding uuids in debug output with indentation formatting the default derived debug of the uuid is quite long.

**Describe the solution you'd like**
Ideally it would render out the UUID in hex or hyphenated format instead.

**Is it blocking?**
It's not super blocking but I find it very frustrating to look at this when debugging.

**Comment by KodrAus** [comment]
Changing the debug format to hyphenated instead of the default for `[u8]` sounds good to me!

**Comment by kinggoesgaming** [comment]
`git blame` points the change to me 😳
