### ISSUE TITLE
Implement PartialEq for &uuid::Uuid

### ISSUE THREAD

**Issue by thedrow** [uuid-rs/uuid#357]
**Is your feature request related to a problem? Please describe.**
I want to compare a Uuid object to a borrowed reference.

**Describe the solution you'd like**
It should be possible to simply compare ```uuid == &other_uuid```.

**Is it blocking?**
None

**Describe alternatives you've considered**
I just borrow.

**Additional context**
None

**Other**
None

**Comment by KodrAus** [comment]
Hi @thedrow :wave:

It looks like most types in the standard library don't implement `PartialEq<T> for &T`, so without some precedent there I think we'd be better off avoiding it here.

**Comment by thedrow** [comment]
I'll take this upstream.
