### ISSUE TITLE
uuid now depends on winapi on all platforms

### ISSUE THREAD

**Issue by ignatenkobrain** [uuid-rs/uuid#362]
This is unfortunate and we (Fedora) would appreciate if you would mark it as needed only on Windows.

Thanks!

**Comment by kinggoesgaming** [comment]
Huh that looks like a misconfiguration on our part... I'll look into it today

**Comment by KodrAus** [comment]
The `winapi` dependency is at least optional, and that crate will compile to nothing on non-Windows platforms.
