### ISSUE TITLE
switch crate publish team access from @uuid-rs/owners to @uuid-rs/uuid

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#368]
Either that or atleast add it as a second team. As the number of projects being published from increase, it will become more and more important to keep separation of power.

**Comment by kinggoesgaming** [comment]
@alexcrichton I believe you have the control over this. can you add @uuid-rs/uuid team to crates.io for uuid?

**Comment by alexcrichton** [comment]
Unfortunately I cannot as I'm not a member, can I add you though? (I probably shouldn't still be on the crate!). Note that there's a lot of other folks too who are added on the crate who could add teams

**Comment by KodrAus** [comment]
@kinggoesgaming Sorry for taking so long! I've added you and @Dylan-DPC as individual owners, removed `uuid-rs/owners` and added `uuid-rs/uuid`.
