### ISSUE TITLE
(C-RELNOTES) Include a Changelog file

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#369]
As part of 1.0.0 release we need to ensure that we include a changelog for our users.

**Comment by kinggoesgaming** [comment]
blocks #191

**Comment by Dylan-DPC** [comment]
I prefer to use "github releases" as a changelog instead of having a separate changelog file. Given the fact, we maintain github releases page to the satisfactory level, we may want to skip this.

**Comment by kinggoesgaming** [comment]
Yes, we have excellent GH Releases release notes. However, generally, it's a good idea to have changelogs provided with the source code. This particularly becomes important when the source is for a fundamental library such as this. 

Also providing changelogs with the source allows people to view changes while being offline if they need.

**Comment by kinggoesgaming** [comment]
Also have a changelog definitely does *not* mean remove the GH Releases release notes.

**Comment by Dylan-DPC** [comment]
Yes, but one will make the other redundant

**Comment by KodrAus** [comment]
I think a changelog can be useful if you add to it over the course of the release as things land. If we wanted to work that way and just copy the relevant part of the changelog into the GitHub release notes then that seems ok to me.

If we don't want to build the changelog that way then I don't think we're likely to put enough work into it for it to be valuable to anybody else.
