### ISSUE TITLE
0.7.3 release on crates.io has all files executable

### ISSUE THREAD

**Issue by ignatenkobrain** [uuid-rs/uuid#384]
This causes errors when packaging in Fedora:

```
BUILDSTDERR: *** ERROR: ./usr/share/cargo/registry/uuid-0.7.3/benches/mod.rs has shebang which doesn't start with '/' ([feature(test)])
BUILDSTDERR: *** WARNING: ./usr/share/cargo/registry/uuid-0.7.3/benches/slog_support/parse_str.rs is executable but has empty or no shebang, removing executable bit
BUILDSTDERR: *** WARNING: ./usr/share/cargo/registry/uuid-0.7.3/benches/slog_support/mod.rs is executable but has empty or no shebang, removing executable bit
BUILDSTDERR: *** ERROR: ./usr/share/cargo/registry/uuid-0.7.3/benches/valid_parse_str.rs has shebang which doesn't start with '/' ([feature(test)])
BUILDSTDERR: *** WARNING: ./usr/share/cargo/registry/uuid-0.7.3/CODE_OF_CONDUCT.md is executable but has empty or no shebang, removing executable bit
…
```

**Comment by kinggoesgaming** [comment]
I am releasing a new version that fixes the docs.rs build. Will include this in it aswell. 

Thanks for reporting @ignatenkobrain

**Comment by kinggoesgaming** [comment]
woops wrong button

**Comment by kinggoesgaming** [comment]
@ignatenkobrain can I get a link to the entire log...

**Comment by ignatenkobrain** [comment]
@kinggoesgaming Unfortunately our Fedora buildsystem thrown it away (since build failed).

But it is not something related to how cargo/rustc works. It is the way we do things. We package crates as sources (basically by copying crate content into /usr/share/cargo/registry) and that's it... And we have checks that if file is executable, it checks shebang and does something with it.

**Comment by kinggoesgaming** [comment]
just realized why it happened.. I recently switched over to using an external hard drive as my primary HDD... apparently, the default perms for it is `-rwxrwxrwx`. Next release should fix it would action

**Comment by kinggoesgaming** [comment]
`0.7.4` is now out
