### ISSUE TITLE
clarification on `Uuid::to_timestamp`

### ISSUE THREAD

**Issue by jstrong-tios** [uuid-rs/uuid#403]
The timestamp returned by `Uuid::to_timestamp` -- is it the number of 100 nanosecond intervals since midnight 15 October 1582? I think so, but wanted to make sure. I'll add to the docs and submit a pull request if this is correct.

**Comment by kinggoesgaming** [comment]
Yes: https://docs.rs/uuid/0.7.4/src/uuid/v1.rs.html#105

**Comment by kinggoesgaming** [comment]
#404
