### ISSUE TITLE
remove the serde_derive dev dependency

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#408]
Currently `serde` and `serde_derive` is pulled for any tests. This is because we didn't have `serde_derive` feature in `serde` enabled before. This caused `serde` to be present in any test round. Now it should be able to isolate `serde` tests

**Comment by kinggoesgaming** [comment]
I am resolving this with merged PR #478

**Comment by daveman1010221** [comment]
So, I was updating some old code and realized that we depended on serde_derive with UUIDs. Is there any way to get this to work with the newer version dependencies of UUID or do I just need to find another way besides UUID? Thanks.
