### ISSUE TITLE
default Uuid::to_string() is hyphenated.  Could we have configurable default? (i.e. to simple?)

### ISSUE THREAD

**Issue by hrbigelow** [uuid-rs/uuid#420]
**Is your feature request related to a problem? Please describe.**
The [Juniper crate](https://docs.rs/juniper/0.12.0/juniper/) uses Uuid's `to_string()` method [here](https://github.com/graphql-rust/juniper/blob/752584fbbdd27961d2641f8033a65e3c5f985d27/juniper/src/integrations/uuid.rs#L13), which automatically outputs the hyphenated version.

[fmt::Display for Uuid](https://github.com/uuid-rs/uuid/blob/33dca9ea8e477f1a817fc5dcfbbc754ac6a66aae/src/core_support.rs#L38)
```
impl fmt::Display for Uuid {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::LowerHex::fmt(self, f)
    }
}
```

[to_hyphenated()](https://github.com/uuid-rs/uuid/blob/33dca9ea8e477f1a817fc5dcfbbc754ac6a66aae/src/core_support.rs#L68)
```
impl fmt::LowerHex for Uuid {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::LowerHex::fmt(&self.to_hyphenated_ref(), f)
    }
}
```

Would it be possible to have a compile-time (or run-time) configuration to specify a different default `to_string` format, such as the non-hyphenated one?

**Describe the solution you'd like**
A `#[cfg(feature = "simple_default_output")]` which provides:

```
impl fmt::LowerHex for Uuid {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::LowerHex::fmt(&self.to_simple_ref(), f)
    }
}
```

instead.

**Is it blocking?**
No, it's just a nice-to-have

**Describe alternatives you've considered**
A feature request to Juniper to allow configuration at that level.  Although, I think the appropriate level would be in the Uuid crate itself.

**Additional context**

**Other**
Other information like relevant issues, external links, etc

**Comment by kinggoesgaming** [comment]
This is not possible. This is purely because of the way Cargo does feature resolution. If you choose one formatting feature and someone else has chosen another formatting feature, there will be compile errors as there are multiple attempts to implement the same thing at the same time.

**Comment by hrbigelow** [comment]
Ahh yes, I understand why that wouldn't work.  How about a runtime configuration function?  I suppose it would make the `to_string()` less efficient since it would have to check a global flag every time.  Would you consider that?

**Comment by kinggoesgaming** [comment]
I think in this instance it might be better to get in touch in with the folks handling the `juniper` crate.
