### ISSUE TITLE
uuid!("") literal macro

### ISSUE THREAD

**Issue by awakecoding** [uuid-rs/uuid#422]
I am looking for a way to specify uuid literals in my code without having to do Uuid::parse_str("<literal>").unwrap(); at runtime. A good example for a different use case is the hex-literal crate (https://crates.io/crates/hex-literal) that makes is easy to specify hex literals with the hex!() macro. In this case, I would like to declare a UUID as a string like "cc58f58b-ca41-4678-b9f9-94ba4eeb9e1e" and have it checked for validity at compile-time to avoid the unwrap().

Maybe the best way would be to have the macro define a byte array to use Uuid::from_bytes() under the hood. Any thoughts?

**Comment by Dylan-DPC** [comment]
Hi. Thanks for creating this issue. 

A macro was always part of our plans but we never found time to implement and polish it. We decided to make it a separate repo. You can find it here: https://github.com/uuid-rs/uuid_macro. If you want to contribute to it, let us know and you are free to do so. Thanks.

**Comment by awakecoding** [comment]
@Dylan-DPC thanks, I didn't know someone had begun working on it!

**Comment by kinggoesgaming** [comment]
Just to add on top of @Dylan-DPC's comment:

The eventual plan is to have the `uuid!` macro available directly with `uuid` crate (as a public dependency exposure) post `1.0` release of `uuid`

**Comment by Hawk777** [comment]
The `uuid_macro` crate has been yanked, but as far as I can tell no macro is available in this crate yet. Are there no macros at this point?

**Comment by kinggoesgaming** [comment]
Yes, it's currently yanked. It was only created for name reservation. We currently don't have plans to actually provide the macro until after 1.0 release.

**Comment by KodrAus** [comment]
@QnnOkabayashi That's true. I think it would be great to have a literal macro in the repository that we could look at re-exporting in `uuid` under a feature gate. We could convert this repository into a workspace and implement here if that's a direction you're interested in.

**Comment by QnnOkabayashi** [comment]
@KodrAus Yes, I think this would be great, and I'm happy to deprecate `compiled_uuid` in favor of a built-in solution. What would the process for converting to a workspace look like? I'm also not familiar with how to exactly create feature gates either.

**Comment by KodrAus** [comment]
Ah that’s a solid approach, but I think we might have to get creative to keep `uuid` itself dependency free by default (to avoid needing to create a `uuid-core`). What we could do is make the parser source shared between `uuid` and the macro crate. So instead of necessarily parsing a `Uuid` we can use the parser to get a shared `[u8; 16]`. That can then be tokenized in the `Uuid::from_bytes` we emit in the macro.

I’m happy to scaffold this all out for you if you wanted to fill in the blanks @QnnOkabayashi?

**Comment by KodrAus** [comment]
@kinggoesgaming We've just merged in a proc macro (that work you did on our error handling works out really nicely for reporting span locations).

I think you're currently the owner of the uuid_macro` crate on crates.io. Would you be happy to add myself and the Owners team to the package so we can publish builds for it along with `uuid`?

**Comment by kinggoesgaming** [comment]
Will do it in the morning… 

it’s 2am and I am trying to fix my broken sleep schedule… I don’t want to stay up till 6am again 🥲

**Comment by kinggoesgaming** [comment]
@KodrAus just had a look. I don’t think I ever did reserve the name. The repo url is currently linking to lassipulkkinen/uuid_macro on GitHub. :(

**Comment by KodrAus** [comment]
@kinggoesgaming Ahh that’s ok 👍 In that case we’ll just come up with a totally different name. It’s just an implementation detail anyways since we can’t define the proc macro in the `uuid` crate.

**Comment by KodrAus** [comment]
Since there's nothing left for us to do here before `1.0` I'll go ahead and close this one now.

Thanks again @QnnOkabayashi for implementing this! And to @kinggoesgaming for the initial work on the parser to make it suitable for end-user error reporting :tada:
