### ISSUE TITLE
Add time-part swapping (swap first and third groups of digits)

### ISSUE THREAD

**Issue by jkoudys** [uuid-rs/uuid#425]
UUIDv1s bytes are organized so that in a left-to-right comparison, when comparing byte-by-byte (or nibble-by-nibble, when comparing string encoded uuids) the bytes that change will be compared first. e.g. if I have:
```
058a119a-dd83-11e9-8a34-2a2ae2dbcce4 
084be782-dd83-11e9-8a34-2a2ae2dbcce4
```
To compare, it'll determine there's not a match by the second char or first byte, rather than compare those 12 shared bytes first. This is often what we want, but if we're building a large set of uuids, that first group of bytes can be ordered by creation time. We can optimize certain cases by sorting so entries with UUIDs closer together in creation time are grouped together.

mysql8 solves this with its "time-part swapping" feature, which deserializes a string uuid into one where the first 4 bytes come last: https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_uuid-to-bin

Alternatively, I suppose rather than decode the Bytes differently, we could use special compare functions so you could sort of build a `BTreeMap` where order is determined by the first 4 bytes.

Not blocking.

**Comment by KodrAus** [comment]
I’ll close this on in favour of #523
