### ISSUE TITLE
Pretty printing in gdb

### ISSUE THREAD

**Issue by EmreAtes** [uuid-rs/uuid#428]
**Is your feature request related to a problem? Please describe.**
It would be nice if gdb printed more user-friendly versions of uuids instead of raw bytes

**Describe the solution you'd like**
I've implemented a pretty printer which uses the lowercase hyphenated representation (below), but I don't know much about rust pretty printers and where the printer would normally go.

for ~/.gdbinit:
```
python    
import sys    
sys.path.insert(0, '~/pretty_printers')    
from uuid_printer import register_uuid_printer    
register_uuid_printer()    
end   
```

for ~/pretty_printers/uuid_printer.py:
```python
import gdb    
    
class UuidPrinter:    
    def __init__(self, val):    
        self.array = val['__0']    
    
    def to_string(self):    
        result = "uuid::Uuid( "    
        for i in range(16):    
            result += "%0.2x" % int(self.array[i])    
            if i in [4, 6, 8, 10]:    
                result += '-'    
        result += " )"    
        return result    
    
def uuid_printer(val):    
    if str(val.type) == "uuid::Uuid":    
        return UuidPrinter(val)    
    return None    
    
def register_uuid_printer():    
    gdb.pretty_printers.append(uuid_printer)    
```

Even if you won't implemented, hopefully this will be useful for some other people that had similar problems.

**Comment by KodrAus** [comment]
Hi @EmreAtes :wave:

Thanks for this! I’m actually not very familiar with pretty printers for gdb and how users typically install and manage them.

It would be nice to see if there’s any convention to lean on for making these available (maybe a `cargo install uuid-gdb`?)

Do you have any thoughts?

**Comment by EmreAtes** [comment]
@KodrAus I'm actually very new to Rust, so I only know that a rust-gdb is installed by rustup, and I learned when trying to pretty print uuids that the pretty printers in rust-gdb are limited to those for the standard library.

I also searched for conventions before sending the issue but I couldn't really find a guide to develop pretty printers for Rust crates.

Maybe if there are some other crates that has pretty printers we can look there? I don't know any though.

**Comment by KodrAus** [comment]
I'm not familiar with any either :)

Maybe there's some conventions in the C++ community we can look at?

**Comment by EmreAtes** [comment]
As far as I could tell from [this issue](https://github.com/rust-lang/cargo/issues/2729) `cargo install` does not support anything other than binary files. I guess anyone who wants to install these printers would have to do it manually.

**Comment by KodrAus** [comment]
Ah I see, so what do you think about creating a new repository in this organization with you as an owner, calling it something like `uuid-gdb` and dropping a copy of the printer along with some instructions in there? We could potentially look at adding some scripts to automate installation in there down the track?

**Comment by KodrAus** [comment]
Alrighty I’ve created [`uuid-gdb`](https://github.com/uuid-rs/uuid-gdb) and added you as a mainter @EmreAtes!

**Comment by kinggoesgaming** [comment]
Closing this issue.

Let’s move discussion over to the uuid-rs/uuid-gdb repository
