### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by nox** [uuid-rs/uuid#431]
I'm looking into bumping `rand` in Servo, could we make a new release with the recent `rand` bump here please?

**Comment by Dylan-DPC** [comment]
thanks @nox. We are working on a 0.8. release but in case this is a high priority, we could probably see if we can cut out a 0.7.x release with the upgrade. Will keep you updated :)

**Comment by nox** [comment]
You can see the upgrade plan on https://github.com/servo/servo/issues/24448, I'm not sure how reactive the other crates' maintainers will be so don't hurry too much. :)

**Comment by kinggoesgaming** [comment]
Actually I was thinking that 0.8 is pretty good to go. The only thing missing is the TODO bits and docs which are not breaking changes so we can move them down to a point release

**Comment by nox** [comment]
Nice! Can’t wait to deduplicate rand in Servo. :)

**Comment by Dylan-DPC** [comment]
Yeah 0.8 is good but will need a review because we want to try and avoid another small major release in case we forgot anything.

**Comment by nox** [comment]
Tell me if I can help in any way.

**Comment by Dylan-DPC** [comment]
We are always welcome to people reviewing the code, and suggesting/implementing changes or implementing anything from one of the issues :)

**Comment by nox** [comment]
Sure, but review what, in that case? The individual PRs were all reviewed before landing, and 0.8 is otherwise ready, so LGTM?

**Comment by Dylan-DPC** [comment]
@nox thanks :)

**Comment by KodrAus** [comment]
We just finished some fairly heavy refactoring in #427 so shouldn't need to break anything for a while. I'm happy to push it out @Dylan-DPC @kinggoesgaming if you're both happy!

I see we've got #432 open but it's a bit open-ended so I think it can wait.

**Comment by KodrAus** [comment]
Done! We've just published [`0.8.0`](https://crates.io/crates/uuid).

**Comment by nox** [comment]
Yep thanks to you two! I'm [on it](https://github.com/servo/media/pull/319) already. :)
