### ISSUE TITLE
ClockSequence Trait Approach

### ISSUE THREAD

**Issue by Dylan-DPC** [uuid-rs/uuid#432]
I know this has already been closed but I think offering a trait to "solve" this problem is the wrong approach.  The default use of ClockSequence here is just plain wrong and should be corrected to follow spec.

_Originally posted by @PrismaPhonic in https://github.com/uuid-rs/uuid/issues/106#issuecomment-542522289_

**Comment by Dylan-DPC** [comment]
@PrismaPhonic can you elaborate on why this approach is wrong? Do you have an alternate approach in mind?

**Comment by kinggoesgaming** [comment]
@PrismaPhonic I would love if you provide the parts that don’t conform with the spec (specifically provide the text in the spec). Because  we are slowly moving to the Big 1.0 release, I want to make sure we can get the correction (if any) and ask for community advice if needed

**Comment by PrismaPhonic** [comment]
Sorry for the delay, been very busy with work this week.  Will try to write something up tonight (I'll edit this comment).

**Comment by kinggoesgaming** [comment]
Thanks :)

**Comment by PrismaPhonic** [comment]
Updated.  Apologies for the long delay!
