### ISSUE TITLE
Update to actix 2.0?

### ISSUE THREAD

**Issue by shirshak55** [uuid-rs/uuid#445]
I think as actix 2.0 is released with async await its a good time to update it right?

**Comment by Dylan-DPC** [comment]
we would love to update it ;) only if we used it as a dependency :D

**Comment by shirshak55** [comment]
@Dylan-DPC sorry it was for this repo but mistakenly published here. 
https://github.com/dessalines/lemmy.

Sorry again thats why i immediately closed.
