### ISSUE TITLE
TryFrom<String> / TryInto<String> traits

### ISSUE THREAD

**Issue by vasilakisfil** [uuid-rs/uuid#457]
Hi Rust newcomer here, but I am wondering the following: how comes this library doesn't implement the `TryFrom<String>` and `TryInto<String>` traits ? Or even `TryFrom<&str>` and `TryInto<&str>`.

**Comment by kinggoesgaming** [comment]
`Try{From,To}` were only recently stabilized. We tended to stay away from nightly features unless they could not be avoided (especially considering our attempts to finally push out a 1.0)

But yes you did a good thing to open this issue @vasilakisfil, hopefully we will have this in the next release.

**Comment by KodrAus** [comment]
These would be good to add now :+1: Thanks for the suggestion @vasilakisfil.
