### ISSUE TITLE
Update documentation: breaking (?) change 7>8; `use uuid::parser::ParseError`

### ISSUE THREAD

**Issue by Luca829** [uuid-rs/uuid#473]
**Is your feature request related to a problem? Please describe.**
I changed the version of `uuid` from 7 to 8.1 and the following statement

```
use uuid::parser::ParseError;
```

gives me the compilation error:
```
error[E0432]: unresolved import `uuid::parser::ParseError`
  --> src/errors.rs:11:5
   |
11 | use uuid::parser::ParseError;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `ParseError` in `parser`
```

**Describe the solution you'd like**
The solution would be to amend the documentation of `uuid` and  add a _breaking change_ from version 7 to version 8

**Is it blocking?**
Yes, but only me alone...

**Describe alternatives you've considered**
I can go back to version 7 and the error is gone. But on the long this is not a solution, IMHO

**Additional context**
I'm playing (trying to replicate/change) with https://github.com/ddimaria/rust-actix-example/blob/master/src/errors.rs

**Other**
Probably the change in the lib implies a refactoring of the mentioned code

https://github.com/ddimaria/rust-actix-example/blob/master/src/errors.rs

**Comment by Dylan-DPC** [comment]
Thanks for creating this issue. yeah we have renamed it [here](https://github.com/uuid-rs/uuid/pull/286). I'm not sure if we mentioned in anywhere, we should add it to the documentation in the next release if it doesn't exist.

**Comment by Luca829** [comment]
Thank you for your feedback. If I try `use uuid::parser::error::Error as ParseError;` I get the error that `parser` is not pub (which is not). I is the `Enum` accessed in the version 8?

**Comment by Dylan-DPC** [comment]
can you try `use::UuidParseError`? (we re-export it iirc)

**Comment by kinggoesgaming** [comment]
@KodrAus should we get this in the next release since this is just documentation

**Comment by KodrAus** [comment]
I think this looks like something that belongs in our release notes. I wouldn't expect to find documentation about changes made between version in the crate docs themselves.

**Comment by KodrAus** [comment]
> can you try use uuid::UuidParseError? (we re-export it iirc)

Ah I think we just have a single top-level `uuid::Error` type now that everything uses. So there aren't individual `ParseError`s or anything like that.

**Comment by KodrAus** [comment]
Since breaking changes are expected between `0.x` bumps I don't think there's anything more to do here, except to spend a little more time on our release notes for the next one 🙂
