### ISSUE TITLE
A new version with getrandom?

### ISSUE THREAD

**Issue by RazrFalcon** [uuid-rs/uuid#475]
Is there are plans on making a new release with `getrandom` instead of `rand`?

**Comment by stjepang** [comment]
Ping - I am also interested in a new release for the same reason.

**Comment by theduke** [comment]
I'm also very interested in this, especially for WASM support of `new_v4()`.

**Comment by kinggoesgaming** [comment]
Hi,

I recently switched from full time Linux to full time windows setup. As soon as I am done setting up my dev env I will try to get the PRs merged and all :)

**Comment by kinggoesgaming** [comment]
Ok so I am thinking tomorrow to start looking into this :)


Sorry for the long pause on development

**Comment by ammgws** [comment]
@kinggoesgaming Is #494 a blocker for this?

**Comment by RazrFalcon** [comment]
Any updates?

**Comment by KodrAus** [comment]
We've added `getrandom` support to the `master` branch. I'm backporting now to `0.8.x` so we can push out a new release with it.

**Comment by KodrAus** [comment]
`0.8.2` has now been published :tada:

I gave the diff a good long look to make sure there weren't breaking changes in there, but that's one of the challenges of infrequent releases!
