### ISSUE TITLE
Unsafe is no longer necessary as of rustc 1.34

### ISSUE THREAD

**Issue by Gaelan** [uuid-rs/uuid#488]
This code (and another identical line in the same file) uses unsafe to convert a `&[u8]` to a `&[u8; 8]`: https://github.com/uuid-rs/uuid/blob/f177d20151f23a8beb9a75df40c736b27dead0d1/src/lib.rs#L360

From Rust 1.34 and on (before that, TryFrom wasn't stable), the following code compiles to the exact same assembly as the code above:
```rust
self.as_bytes()[8..16].try_into().unwrap()
```

Tested with rustc 1.34 and 1.45.2 on godbolt.org, with `-O`.

The `try_into` version is simpler and doesn't use unsafe, so it'd probably be a good idea to switch to that once support for Rust 1.32/33 is dropped.

**Comment by kinggoesgaming** [comment]
Our current MSRV is 1.32.0 😞 

However I will keep the issue open so we can update the relevant code when we get to it

**Comment by KodrAus** [comment]
We've just bumped our MSRV to `1.34.0` in #501 with an update to `getrandom`.

Would anybody like to submit a PR for this?
