### ISSUE TITLE
Parse microsoft GUIDs

### ISSUE THREAD

**Issue by roblabla** [uuid-rs/uuid#513]
**Is your feature request related to a problem? Please describe.**

Microsoft GUIDs are often formatted as an UUID surrounded by curly braces, e.g. `{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}`. The `Uuid::from_str` function does not currently parse this format. 

**Describe the solution you'd like**
`Uuid::from_str` should accept UUIDs surrounded by curly braces.

**Is it blocking?**
No, it's merely a minor inconvenience.

**Other**

- GUIDs in the Windows Installer: https://docs.microsoft.com/en-us/windows/win32/msi/guid
- GUIDs in the Windows EventLog: https://docs.microsoft.com/en-us/windows/win32/wes/eventschema-guidtype-simpletype
- Windows Registry also stores GUID in this format.

**Comment by kinggoesgaming** [comment]
IIRC this was intentional, as this crate was meant just to handle the formats as provided by the specification.

However since then we have added support for `GUID` from `winapi` crate itself, so we "could" support it. What say you @KodrAus?

**Comment by KodrAus** [comment]
They're quite a common format on Windows and it looks like C# does parse them. It seems reasonable to me since we can tell from the first character whether what we're looking at could be a Microsoft GUID.

**Comment by kinggoesgaming** [comment]
@KodrAus While we are on the topic of moving the GUID support into its own crate, what are your opinions on this one?

**Comment by KodrAus** [comment]
I think we could still support parsing GUIDs in UUID itself. The only reason for splitting `winapi` support out is so we don’t end up with unstable `winapi` types in our stable `uuid` API 🙂
