### ISSUE TITLE
Unable to Active v4 Feature for Example

### ISSUE THREAD

**Issue by ca-mantis-shrimp** [uuid-rs/uuid#522]
**Describe the bug**
Im just trying to write some learning tests and i'm having trouble enabling the "v4" feature for this crate.

**To Reproduce**
main.rs
```rust
use uuid::Uuid;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    #[cfg(feature = "v4")] {
        let my_uuid = Uuid::new_v4()?;
        println!("{}", my_uuid);
    }
    Ok(())
}
```
Cargo.toml
```Toml
[dependencies]

[dependencies.uuid]
version = "0.8"
features = ["serde", "v4"]
```

I've tried every permutation of the dependency setup but I can't get this example build to run! it runs successfully, but just doesn't do anything
**Expected behavior**
the example of building a v4 UUID and Printing it runs
**Screenshots**
![main with LSP diagnostics](https://user-images.githubusercontent.com/25948785/127408844-69c97aa1-f81b-434d-821b-6fb68cd1a00b.PNG)
![run example](https://user-images.githubusercontent.com/25948785/127408863-a7917332-c80e-4615-aa03-99cd067159f5.PNG)

**Additional context**
Windows on WSL if that matters, but i don't think it should?

**Comment by ca-mantis-shrimp** [comment]
I made it work after I removed the `?` and the cfg directive. don't know why the cfg directive broke it since it was only supposed to check but I got it working now after seeing #521

**Comment by Dylan-DPC** [comment]
if you were writing this test in a separate project you don't need to feature gate it since the feature will always be enabled as you have mentioned it in Cargo.toml.
