### ISSUE TITLE
Add `Display`, `LowerHex` & `UpperHex` alternate flag support

### ISSUE THREAD

**Issue by malobre** [uuid-rs/uuid#532]
`Display`, `LowerHex` & `UpperHex` have an alternate format you can use with `{:#}`, `{:#x}`, `{:#X}` respectively.
It would be great for the alternate format to use the `Simple` formatter such that:

format | output
-------|-------------------------------------
`{}`   |`1b5eac77-9d6b-42b5-8705-1e7b52d46109`
`{:#}` |`1b5eac779d6b42b587051e7b52d46109`
`{:x}` |`96dbdce3-987b-4196-8973-747e27a5eacc`
`{:#x}`|`96dbdce3987b41968973747e27a5eacc`
`{:X}` |`97C615A8-F737-49DB-A468-C60DC1935012`
`{:#X}`|`97C615A8F73749DBA468C60DC1935012`

**Comment by KodrAus** [comment]
Thanks for the suggestion @malobre! This seems reasonable to me :+1:
