### ISSUE TITLE
Implement `Serialize` & `Deserialize` for `Hyphenated`

### ISSUE THREAD

**Issue by thomaseizinger** [uuid-rs/uuid#534]
**Is your feature request related to a problem? Please describe.**

Would like to derive `Serialize` on a newtype that wraps `Hyphenated`.

**Describe the solution you'd like**

`derive(Serialize, Deserialize)` to just work.

**Is it blocking?**
-

**Describe alternatives you've considered**

Manually implement `Serialize` on my newtype. Works but is verbose.

**Additional context**
-

**Other**
-

**Comment by thomaseizinger** [comment]
> Hey @thomaseizinger 👋
> 
> I think this is just a missing bit of functionality 🙂 Would you be happy to PR a `Serialize` implementation for our format adapters?

Sorry, I've been on vacation and you beat me to it, otherwise would have happily sent a PR!

Thank you!

**Comment by Kek5chen** [comment]
Hello, excuse me but I don't think this is closed. #546 implemented Serialize, but not Deserialize on the Format Variants.
