### ISSUE TITLE
Minor docs change

### ISSUE THREAD

**Issue by QnnOkabayashi** [uuid-rs/uuid#568]
We should make sure to emphasize that the macro is for string literals only, and that it parses at compile time.

So this part should be altered slightly.
https://github.com/uuid-rs/uuid/blob/b98c9586c1359a5cc354defe20d8ea31e58f29f0/src/lib.rs#L60-L66

... to instead say:
```rust
 //! If you have a UUID value, you can use its string literal form inline:
```

**Comment by kinggoesgaming** [comment]
Another way can we to have a note at the bottom  warning that only string literals are accepted.

```rust
//! If you have a UUID value you can use it inline: 
 //! 
 //! ``` 
 //! use uuid::{uuid, Uuid}; 
 //! 
 //! const ID: Uuid = uuid!("67e55044-10b1-426f-9247-bb680e5fe0c8"); 
 //!
 //! __NOTE__: Only `string literal`s are accepted by the macro. If you intend on using a `number literal`s, instead using `Uuid::from_u128(...);`
 ```
