### ISSUE TITLE
`Uuid::parse_str` doesn't really require utf8

### ISSUE THREAD

**Issue by derekdreery** [uuid-rs/uuid#570]
I see that `Uuid::parse_str` immediately converts the `str` to `[u8]`. Could the method instead accept `impl AsRef<[u8]>`, or alternatively could there be a `parse_bytes` method (with name bikeshedding, e.g. `parse_ascii`) for when you don't have validated utf8. My motivation is parsing some XML with Uuids embedded in them. With quick-xml you get things as [u8] for speed (with the option to convert to utf8, taking into account the document encoding). It seems a shame to parse the uuids into utf8 to immediately discard that information.

For my use case the performance probably isn't critical, but could potentially be important if you were parsing a very large amount of xml with lots of GUIDs/UUIDs.

**Comment by derekdreery** [comment]
If you decided to go for this feature request, I'd probably favour `parse_ascii` as this asserts that the bytes input mustn't be encoded in something like utf16, or else the method won't work.

**Comment by KodrAus** [comment]
`parse_ascii` sounds like a good name to me :+1: We already use the term _bytes_ to mean a specific 16-byte value so that might get confusing.

**Comment by Nugine** [comment]
|method|parameter|error|speed|const|
|-|-|-|-|-|
|`Uuid::parse_str`|`&str`|detailed|slower|no
|`Uuid::try_parse`|`&str`|ambiguous|faster|yes|

How about renaming `Uuid::try_parse` to `Uuid::parse_ascii` and changing its parameter to `&[u8]`?
Drawback: it may break how `InvalidUuid` works.

https://github.com/uuid-rs/uuid/blob/2d6c147bdfca9612263dd7e82e26155f7ef8bf32/src/error.rs#L59-L61

**Comment by KodrAus** [comment]
@Nugine Ah, since that's already the sad path we could add a `BadEncoding` variant to the error and turn that into a regular `from_utf8`? For `try_parse` we wouldn't be able to use `AsRef<[u8]>` though, would we. It would need to be `&[u8]`, which is also a reasonable input type I think.

**Comment by KodrAus** [comment]
It would be good to avoid breaking things now that they've shipped, even though what we've got is an alpha release. I think we might be better off simply adding a `const fn try_parse_ascii` that accepts a `&[u8]` and leaving `parse_str` as "soft-deprecated", with the intention that `try_parse` will do the same work in its error path once it's possible in `const` without penalizing its really nice happy-path performance.

What do you think @Nugine?

**Comment by Nugine** [comment]
> Ah, since that's already the sad path we could add a `BadEncoding` variant to the error and turn that into a regular `from_utf8`? 

The sad path happens in `InvalidUuid::into_err` which only affects the macro diagnostics. So I think it's ok.

> For `try_parse` we wouldn't be able to use `AsRef<[u8]>` though, would we because it's `const`. It would need to be `&[u8]`, which is also a reasonable input type I think.

Yes. The parameter must be `&[u8]`. The macro can restrict the input type to be `&core::primitive::str`.

> It would be good to avoid breaking things now that they've shipped, even though what we've got is an alpha release. 

It's the last chance to change the api. I think we should prefer the best design to the compatible design.

**Comment by KodrAus** [comment]
> It's the last chance to change the api. I think we should prefer the best design to the compatible design.

That’s a fair point, but I actually think that chance was before we shipped `1.0.0-alpha.1` and we have to get used to a different way of working now 🙂 Unless something is really broken in this release I think we should avoid any breakage before promoting it to `1.0.0`. The main reason I’m trying to push back on these now is just so we don’t end up in limbo with these alpha releases wanting to keep pushing little last minute changes in. That’s a trap I’ve fallen into in other places (I’ve got a `1.0.0-alpha.8` of another library floating around). They’re also all semver compatible so if we break things users don’t necessarily get a chance to opt-in in their own time.

The end state of `Uuid::try_parse(&str)` and `Uuid::try_parse_ascii(&[u8])` (with `parse_str` deprecated and hidden) does seem like a nice API to me.

**Comment by Nugine** [comment]
> The main reason I’m trying to push back on these now is just so we don’t end up in limbo with these alpha releases wanting to keep pushing little last minute changes in.

It makes sense. :joy:

> The end state of `Uuid::try_parse(&str)` and `Uuid::try_parse_ascii(&[u8])` (with parse_str deprecated and hidden) does seem like a nice API to me.

It looks nice even through `Uuid::try_parse(s)` is just a shorter version of `Uuid::try_parse_ascii(s.as_bytes())`.

**Comment by kinggoesgaming** [comment]
> That’s a fair point, but I actually think that chance was before we shipped 1.0.0-alpha.1

I think we can release a `1.0.0-alpha.2`. A gotcha catch-all release

The way I think is that we are introducing `-lpha.x` releases is to capture any last API changes that can be made. That designation should be enough for anyone using the alpha releases that breakages are unlikely, but not 100% impossible

**Comment by KodrAus** [comment]
The way I see it, this is our first opportunity as a project to try rationalize a new feature into our stable API, so using the alpha status as an escape hatch to make breaking changes to fit it is an incentive for us to keep deferring stabilization. It’s a tough transition to make for sure, but I really think we’ve put together a nice, usable, and consistent library here over the last few years, and should trust our design decisions 🙂 We don’t need to break things, we’ve got a great foundation already.

**Comment by derekdreery** [comment]
As a library user, I personally don't care if there is a new strictly speaking redundant method called parse_ascii (rather than the original). I just want the function that does what I want.
