### ISSUE TITLE
Security Policy

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#574]
Before we do release `1.0,0`, we need to determine how we deal with any vunerablilities that show up in the crate or any deps that we have.

Also setup the Security Policy file.

**Comment by KodrAus** [comment]
This sounds like a great idea!

**Comment by KodrAus** [comment]
Did you have any thoughts on what should go in there @kinggoesgaming?

**Comment by kinggoesgaming** [comment]
Will brainstorm on this on my commute to work tomorrow

**Comment by kinggoesgaming** [comment]
So after sleeping over the matter, I think these these questions need to be addressed:

Who/ How to contact?
- needs to be a private means

Time to contact the reporting party?
- First action
- Affected versions
- Further steps
- etc

Security support lifetime?

What to do when we cannot resolve a vulnerability in a version due to MSRV?

What versions are considered LTS?

What about `0.8.x`?

How to publicly report the vulnerability?
- Timeframe
- Resolution steps
- Where to publish?

What versions are just to be yanked vs get a update version?

Register a CVE/ RUST-SEC id?

Disclosure policy?

Update policy?

---

@KodrAus if you think you have any other questions/ issues raise, add to the list.

For the matter of clarity it's best to either do each point as a separate comment; or move this to Discussions.

**Comment by kinggoesgaming** [comment]
I will start adding my 2 cents tonight after work
