### ISSUE TITLE
Tracking issue for defmt

### ISSUE THREAD

**Issue by KodrAus** [uuid-rs/uuid#638]
This issue is a place to keep anybody using the unstable `defmt` feature up-to-date on any changes being made to it.

In order to use `defmt`, you need to opt-in not just to the feature, but to the `uuid_unstable` RUSTFLAGS configuration too. We can make breaking changes to `defmt` at any point, but still want to be considerate of anybody making use of it, so will try keep open about any version bumps or other breakage that's coming.

**Comment by KodrAus** [comment]
This wasn't implemented in the end, because `defmt` can't be depended on by libraries.

**Comment by guissalustiano** [comment]
Sorry @KodrAus, can you explain a little further why `defmt` can't be depended on by libraries?

**Comment by KodrAus** [comment]
@guissalustiano It looks like I never fully linked up or articulated what happened when we tried to do this last time. The problem is described here: https://github.com/knurling-rs/defmt/issues/673#issuecomment-1142150012

As I understand it, `defmt` is only meant for microcontrollers and doesn't build on full OSes. That makes it unsuitable as a dependency for libraries targeting broad compatibility. Even as an optional dependency it breaks `--all-features`, which I do want to keep working.
