### ISSUE TITLE
Add bytemuck support

### ISSUE THREAD

**Issue by John-Toohey** [uuid-rs/uuid#710]
I am using `Uuid`s with `bevy_ggrs_rollback`, which requires `bytemuck` compatible types for  serialization and deserialization. By adding the `bytemuck` feature, it would thus become possible to use `Uuid` with said library (and other similar libraries). Whilst it is possible to do this by using a newtype or the `as_u128` and `from_u128` methods directly, I believe that adding bytemuck support will make code using bytemuck cleaner.

Thank you for your time,

John T

**Comment by KodrAus** [comment]
This is available as of `1.5.0`
