### ISSUE TITLE
Add `prost::Message` implementation for `Uuid`

### ISSUE THREAD

**Issue by jwilm** [uuid-rs/uuid#715]
## Motivation
[Prost](https://github.com/tokio-rs/prost) is a [Protocol Buffers](https://developers.google.com/protocol-buffers/) implementation for the [Rust Language](https://www.rust-lang.org/). Protocol Buffers are used as the message exchange format for [gRPC](https://grpc.io/). Clients and servers need to build and parse protocol messages. The Prost crate has a code generator to transform .proto files into Rust types that implement the `prost::Message` trait to simplify message encoding/decoding. When working with `Uuid`s, it's common to have to write boilerplate to handle transforming between whatever the code gen'd type is and the proper `Uuid` type.

## Solution
The Prost crate has support to use existing Rust types rather than generating new types provided those existing types implement the `prost::Message` trait. Thus, the solution is to add a `prost::Message` implementation behind a feature flag.

```rust
// Raw encoding
#[cfg(feature = "prost-bytes")]
impl prost::Message for Uuid ..

// String Encoding
#[cfg(feature = "prost-hyphenated")]
impl prost::Message for Uuid ..
```

One challenge is that Protobuf users may require a particular encoding format, and so a decision would need to be made about which formats to support or whether to support all the encoding formats implemented by this crate. I have included the two more common formats in the above example, but perhaps a user would need an alternative encoding like urn.

## Alternatives
- Continue writing boilerplate to convert between a generated Uuid struct (typically the equivalent of `struct Uuid(Vec<u8>)` and the uuid-rs `Uuid` type.
- Implement a 3rd crate to get around the orphan trait rules; this still requires a newtype and some boilerplate but is a bit less boilerplate than the first alternative.

## Is it blocking?
No

## Anything else?
Prost is a rather mature crate in the tokio organization that has quite a bit of adoption and has likely cemented its place in the Rust ecosytem. Adding a feature to interoperate with prost is unlikely to result in feature churn.

**Comment by KodrAus** [comment]
Hi @jwilm! :wave:


Thanks for the suggestion. I'm a bit uneasy about baking in a particular protobuf encoding for UUIDs in this library because there doesn't appear to be a well-known type defined for them.

If we did support this, I wouldn't want to use mutually exclusive features to pick an encoding, partly because mutually exclusive features break `--all-features` builds, and partly because I can imagine a system ending up needing to integrate with services that use different UUID encodings. I can't really think of a compelling alternative though, since you're not necessarily in control of the protos so can't just pick a type for UUID fields that more accurately describes the desired encoding.

As much as boilerplate can be a nuisance, I think that's probably the most appropriate solution here.

**Comment by jwilm** [comment]
Hey @KodrAus,

Thanks for sharing your perspective. The point around needing to integrate with services leveraging different encodings is something I hadn't considered with the initial proposal.

I wonder if it might make sense to pick a relatively common encoding to support natively on the Uuid type so that new applications are able to build boiler-plate and existing applications have the opportunity to migrate if desired. The status-quo would still allow supporting alternative encoding formats.

Perhaps the right decision for now is to wait until prost matures a bit and see what other options might be possible in the future. Maybe prost can figure out a way to support well known 3rd party types like Uuid, without direct coupling, and leaving encoding formats up to the application.

**Comment by KodrAus** [comment]
For what it's worth, I am kind of surprised there's no well-known type for UUIDs, since 128bit identifiers are _so_ common. I guess it does make some sense though, since protobuf doesn't have any I128 type, so the most compact encoding is still going to be 17(?) bytes.
