### ISSUE TITLE
1.7.0 breaking change

### ISSUE THREAD

**Issue by andrewweston** [uuid-rs/uuid#729]
1.7.0 has dropped the `wasm-bindgen` feature flag making it incompatible with previous versions (<= 1.6.1). I am having issues updating as a 3rd-party dependency that is using the `uuid` library with the `wasm-bindgen` feature flag.

I have pinned the version to `1.6.1` for now, so not a showstopper.

Perhaps an option may be to use the [semver trick](https://github.com/dtolnay/semver-trick) as a workaround?

**Comment by KodrAus** [comment]
Hi @andrewweston 👋

Thanks for pointing this out! The `wasm-bindgen` dependency was never meant to be public. It was only a Cargo limitation that made it so. Packages should instead use the `js` feature. If that dependency in question is up on GitHub somewhere I can possibly send a PR their way.
