### ISSUE TITLE
Why does Uuid implement Ord, PartialOrd?

### ISSUE THREAD

**Issue by timvisee** [uuid-rs/uuid#742]
The `Uuid` type [derives](https://github.com/uuid-rs/uuid/blob/fe11291cc0ed83ee5bc2534f21f3c043a93f5e26/src/lib.rs#L437) `Ord` and `PartialOrd`.

What is the reasoning behind implementing these? Aren't comparisons meaningless here, since we're essentially comparing random data?

I believe these are incorrect, and if so, they should be removed.

**Comment by KodrAus** [comment]
@timvisee For v4 UUIDs it doesn’t make a lot of sense, but v6 and v7 UUIDs are laid out to be byte-wise sortable. For these variants the ordering does make sense.
