### ISSUE TITLE
Monotonicity of UUIDv7 generated within a millisecond.

### ISSUE THREAD

**Issue by MasahikoSawada** [uuid-rs/uuid#773]
Hi,

I tried to generate 10 UUIDs (version 7) in a loop by the following simple program:

```rust
use uuid::Uuid;
use uuid::Timestamp;
use uuid::NoContext;

fn main() {
    for _i in 1..10 {
        let id = Uuid::new_v7(Timestamp::now(NoContext));
        println!("{}", id);
    }
}
```

However, the generated UUIDs seems not to be monotonically increased:

```
% cargo run
   Compiling uuid-test v0.1.0 (/home/masahiko/work/uuid-test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/uuid-test`
019303ac-7a6a-7783-a247-69023f93a8bb
019303ac-7a6a-702f-a49b-1ac3ffc328c5
019303ac-7a6a-748f-9163-2983089d4dbe
019303ac-7a6a-7896-92e9-9c343796aab6
019303ac-7a6a-7288-8a2d-ba127b89ad1d
019303ac-7a6a-7f4c-a924-af333b9247f9
019303ac-7a6a-7174-937e-8829a4c4b072
019303ac-7a6a-716a-95c1-2e1e8041de7e
019303ac-7a6a-7c5b-be5f-30b9e4d7b230
```

Is the monotonicity not guaranteed for UUIDs generated in the same millisecond?

FYI I used "1.11.0" uuid crate.

**Comment by mertalev** [comment]
I think the official uuidv7 spec only specifies millisecond precision, but allows a number of bytes that can be used for microsecond precision. I'd be very interested in a flag to use microsecond precision.

**Comment by KodrAus** [comment]
Hi @MasahikoSawada :wave: The [`NoContext`](https://docs.rs/uuid/latest/uuid/timestamp/context/struct.NoContext.html) type doesn't guarantee monotonicity within a millisecond, but the [`ContextV7`](https://docs.rs/uuid/latest/uuid/timestamp/context/struct.ContextV7.html) type does. If you need sub-millisecond monotonicity then `ContextV7` is the type to use.

**Comment by KodrAus** [comment]
@mertalev This sounds like #767, which I think we'll support through another `Context` implementation.

**Comment by MasahikoSawada** [comment]
Thank you. I didn't know ContextV7, and confirmed it works expectedly with ContextV7.
