### ISSUE TITLE
Unfinished documentation

### ISSUE THREAD

**Issue by matiu2** [uuid-rs/uuid#776]
There's an unfinished sentence here: https://github.com/uuid-rs/uuid/blob/main/src/v7.rs#L34

"The data will be ..." I don't know what it will be :(

Thanks for a great and free product :)

**Comment by KodrAus** [comment]
Oh it looks like it is cut off right when the sentence is about to become useful.

That will be saying:

> A v7 UUID can be created from a unix [`Timestamp`] plus a 128 bit random number. When supplied as such, the data will be combined to ensure uniqueness and sortability at millisecond granularity.
