### ISSUE TITLE
Is serde implementation going to be stable?

### ISSUE THREAD

**Issue by mulkieran** [uuid-rs/uuid#90]
Hi!

Are you going to stick with hyphenated format for all time?

**Comment by radix** [comment]
There's no action item in this issue: @mulkieran is there something you're requesting be done? Does the merge of #104 resolve your concerns?

**Comment by mulkieran** [comment]
Thanks for bringing this change to my attention. I think the short answer to my question _and_ yours is "No". But feel free to close the issue, I think we can deal.
